### ISSUE TITLE
Using an external db instead of file.

### ISSUE THREAD

**Issue by leyluj** [schollz/goagrep#10]
Ok, I'm new to **String Fizzy matching**, **go-lang** and **goagrep** so please, bear with me.

How can I search a list of names in a db with your package?

I'm using POSTGRESQL db.

**Comment by schollz** [comment]
If you're not using **go-lang** then you can simply download [the latest release](https://github.com/schollz/goagrep/releases) to use as a package. That way you don't have to learn any **go-lang**! You can just run the package.

I've never used POSTGRES, but I do use **goagrep** with SQLITE. First, what you want to do is dump the keys that you want to search over into a textfile, e.g. `names.txt`. Then you would run:

`goagrep build -l names.txt -d names.db`

 which will build a indexing file called `names.db`. Then, when someone gives you a name, you can first search it in the **goagrep** db using 

`goagrep match -d names.db -w SOMENAME` 

which will give output like `BESTNAME|||score`. Now use that `BESTNAME` in your POSTGRES query. That's it!

_Some caveats:_ **goagrep** is only really useful if you have a HUGE list of names and that your list of names doesn't change that often. Basically every time your list of names changes, you'll have to rebuild the **goagrep** index database. This doesn't take long (~seconds) so you can easily do this as long as new names are occurring that frequently.  Second caveat is that you don't need **goagrep** if you can do a POSTGRES query to decrease the number of possible names. E.g. if you can do `select NAME where date=X and age=Y` then you would no longer have a _huge_ list of names, and you can do something simpler like [using the Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) on the small set.
