### ISSUE TITLE
Add runtime option to build db

### ISSUE THREAD

**Issue by derekperkins** [schollz/goagrep#12]
I'd love to be able to build a db on the fly without having to use the filesystem. This could be used in conjunction with #10 to create the index on instance startup for example.

```
func GenerateDBFromStrings(strings []string, databasePath string, tupleLength int, verbosity bool)
```

**Comment by schollz** [comment]
That's a great idea. It easy to generate the db (its really just two maps), but I'd need to generalize the matching functions to accommodate it. I'll play around with it!

**Comment by schollz** [comment]
So you can build the db on the fly now:

``` golang
wordlist := "someWordList.txt"
tupleLength := 3
verbose = false
words, tuples := goagrep.GenerateDBInMemory(wordlist, tupleLength, verbose)
```

And then `words` and `tuples` can be fed to get matches:

``` golang
wordToMatch := "something"
matches, matchDistances, _ := goagrep.GetMatchesInMemory(wordToMatch, words, tuples, tupleLength, false)
```

Still a little complicated since you have to carry around the two variables `words` and `tuples`. I'll try to do some refactoring later for making a structure for this.

**Comment by schollz** [comment]
Added in https://github.com/schollz/goagrep/commit/6e4291fc0d9607809fc4c12b4c10bca801a6744e
