### ISSUE TITLE
Decouple BoltDB

### ISSUE THREAD

**Issue by derekperkins** [schollz/goagrep#13]
Scanning through the code, I'm wondering how difficult it would be to decouple BoltDB. If you made a simple interface, you should be able to swap out BoltDB for just a simple in memory map for smaller datasets. That wouldn't require any external assets and should perform even faster.

**Comment by schollz** [comment]
So based on this I implemented a "in-memory" option and as an example, you can use the CLI utility as a TCP server which holds everything in memory.

I don't think this is exactly what you're saying, but its a step in the right direction. The code needs to be refactored a bit before I can make an interface to swap out Bolt...

Their are new benchmarks on the README, which shows nice improvement for in-memory operations.

**Comment by derekperkins** [comment]
Wow! Thanks for being so responsive! This will be perfect for my use case. I have ~100k city, state, country or zipcodes to fuzzy match on, feeding a typeahead api lookup. It's fast and I rarely deal with any sort of memory pressure.

> I don't think this is exactly what you're saying, but its a step in the right direction. The code needs to be refactored a bit before I can make an interface to swap out Bolt...

Looking at your implementation, I'm not sure that an interface is necessary. I doubt that you'll really need more than the two options. People can use in-memory if they have the RAM or the BoltDB implementation for larger datasets. I doubt people will be clamoring to swap out their own storage engine for it. :)

**Comment by schollz** [comment]
Great, glad it will work for you. Let me know if you find any bugs!
